version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  server:
    build: .
    working_dir: /app/api
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build: .
    working_dir: /app
    command: node worker.js
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
